apiVersion: v1
kind: ServiceAccount
metadata:
  name: explainv-webui
  namespace: explainv
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: explainv-webui
  namespace: explainv
rules:
  - apiGroups: ["apps"]
    resources: ["statefulsets"]
    verbs: ["get", "list", "update", "patch"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "delete"]
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get", "list", "create", "update", "delete"]
  - apiGroups: [""]
    resources: ["endpoints"]
    verbs: ["get", "list", "create", "update", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: explainv-webui
  namespace: explainv
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: explainv-webui
subjects:
  - kind: ServiceAccount
    name: explainv-webui
    namespace: explainv